#POST http://localhost:8080/api/users/createUser
#
#{
#  "name": "test",
#  "surname": "surname",
#  "login": "test",
#  "password": "pwd",
#  "email": "email",
#  "phoneNumber": "123"
#}

GET http://localhost:8080/api/example/protected?token=eyJhbGciOiJSUzI1NiJ9.eyJpZCI6NSwicm9sZSI6IkFETUlOIn0.NtvyZA3XoTl-8Y7YP4cHqzkhZi1JyFVUjQfw3iESnff5JUXoFvPqk64zyb8n1b1PNYD1mB6x62SS8UQz90RBaA6mrJ-Rl4xEx1z7s7Cdu_4QuW50rnbj8O0q3c8VhaInrl7VBoO3CntXJR3ik2e-N6f4-tmvY_cfCawEi4x0IDwJPBQt1YBET85hG9NG2vSiANQcycY1Sc6yFTWgnlOw81X0gEw2Yzfd6UolQYTdxOehtm9YGjrmm_m5oMVc_8CEWdAHG1f4-TdVaQkmkHBOuoUFXd35hNvqmP3QS-be0M8xVy6ieIJS_Ph9UGz7keYV0A3yplEKy2YBwjwYAsd0Jw
Authentication: Bearer